### PR TITLE
nuke the site nav

### PR DESCRIPTION
**Pull request by Artoria2e5**
this is the thing making titles appear when we dont want them to. go away

see rms-open-letter/rms-open-letter.github.io#2519

### CODE REVIEW

**Comment by Artoria2e5** [comment]
@ehashman i am extremely sorry that the non-fancy headings broke it too. on the good side i think i finally figured it out.

**Comment by ehashman** [comment]
> @ehashman i am extremely sorry that the non-fancy headings broke it too. on the good side i think i finally figured it out.

No problem at all! Mistakes happen :laughing: That's what the revert button is for.

I will YOLO merge this and revert if it breaks anything.

**Comment by ehashman** [comment]
The Chinese titles seem to have reappeared?! That's bizarre. Let me double check and revert.

**Comment by ehashman** [comment]
@Artoria2e5 did that happen when I merged them with the markdown headers? I am not sure why this is happening...

**Comment by ehashman** [comment]
Okay! It's fixed! Just had to push another commit to the site to rebuild. We are all set :partying_face:

**Pull request merged**
